### ISSUE TITLE
Do we need batch here?

### ISSUE THREAD

**Issue by zivzone** [kennyvoo/face-occlusion-generation#9]
Hi,
Thanks for your repo. I', wondering do we needs batch here?
[        for batch in range (batch_size):](https://github.com/kennyvoo/face-occlusion-generation/blob/a35da5a72af2c246050defa825436634b6a89413/utils/colour_transfer.py#L64)
I guess you just put one src image and one occ image as a pair into 
[color_transfer_sot](https://github.com/kennyvoo/face-occlusion-generation/blob/a35da5a72af2c246050defa825436634b6a89413/utils/colour_transfer.py#L32)

BR,
Ziv

**Comment by kennyvoo** [comment]
The batch side here refers to the solver batch instead of the image batch. This function supposes to take in 1 image pair as input. Although this function is taken from [DeepFaceLab](https://github.com/iperov/DeepFaceLab/blob/master/core/imagelib/color_transfer.py#L8) as mentioned in the code, It was originally from this [source](https://dcoeurjo.github.io/OTColorTransfer/). You can refer to this website for more information about color transfer via sliced optimal transport.

**Comment by zivzone** [comment]
Hi, @kennyvoo 
Ok, I see. Thanks for your reply!
